name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Sleep Randomly
      run: |
        sleep_time=$(( RANDOM % 21600 ))  # Sleep up to 6 hours
        echo "Sleeping for $sleep_time seconds"
        sleep $sleep_time
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
